fontSize: 18
previewFontSize: 14

database:
  useDatabase: false
  type: sqlite
  mysql:
    host: localhost
    port: 3306
    user: root
    password: root
    database: my_database
  sqlite:
    path: path
    database: database.db